name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          version: "0.12.19"
      - name: Run tests
        run: uv run --locked --extra controller python -m unittest discover -v
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
